### ISSUE TITLE
the test model looks like based on cuda device

### ISSUE THREAD

**Issue by knowasdf** [InterDigitalInc/HRFAE#3]
Hi bor:
when I try to run test.py, and when the code go into **line 58**:
trainer.load_checkpoint(log_dir + 'checkpoint')
then an error happend at here.
'''
_raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU._
'''
this looks like means I must run these code on a cuda device.
or because of this test model is trained on a cuda device, I must build a new model which supported on CPU only?

**Comment by Xu-Yao** [comment]
Hello knowasdf, I tried to reproduce the issue but did not succeed. I searched your question and find this [https://stackoverflow.com/a/59499754](url). So I propose to replace the line 219 of trainer.py by 
""" 
state_dict = torch.load(checkpoint_path, map_location={'cuda:0': 'cpu'})
"""
I hope that could help you solve the problem :)

**Comment by hi589dsTq92** [comment]
Hey bro: 
  cool job!! it's WORKING now.
  for adaptability, I revised some code like these: 
**trainer.py** at line 218,219: 
    _def load_checkpoint(self, checkpoint_path, device={'cuda:0': 'cpu'}):
        state_dict = torch.load(checkpoint_path, device)_
**train.py** at line 77: 
    _epoch_0 = trainer.load_checkpoint(opts.checkpoint, device)_
**test.py** at line 56: 
    _trainer.load_checkpoint(opts.checkpoint, device)_
**test.py** at line 58: 
    _trainer.load_checkpoint(log_dir + 'checkpoint', device)_

;)

**Comment by bingo9062** [comment]
hi bro:
Is it convenient for you to provide the model after training and more detail?
The ffhq data is too large. I don't know how to continue after I modify code in your way.
i would like to use this code on cpu too,
thanks!
